WITH base AS (
SELECT
    t200.PNR_REF,
    t200.TRAVLR_UCI,
    t200.TRAVLR_FIRST_NAME,
    t200.TRAVLR_LAST_NAME,
    t240.AAIRALPC,
    t240.PRMEFLTN,
    t240.LOCLDEPD,
    t240.DEPUPOR,
    t240.ARVLPOR,
    x.ACTIVITY_TSMP AS BAG_TAG_UTC_TIMESTAMP,
    x.USER_SONIC_ID AS BAG_TAG_USER_SONIC_ID,
    x.OFFICE_ID     AS BAG_TAG_OFFICE_ID,
    t261.HIST_TRANS_ID,
    t261.TRANS_SEQ_NO,
    t261.HIST_TEXT AS BAG_TAG_NUMBER
FROM PQMF.QHB0240_FLIGHT_LEG_DEPART t240
JOIN PQMF.QHB0241_TRAVLR_FLIGHT_LEG t241
  ON t240.FMFL_ID = t241.FMFL_ID
 AND t240.FL_VERSION_NO = t241.FL_VERSION_NO
JOIN PQMF.QHB0221_FLIGHT_ITINERARY t221
  ON t241.TRAVLR_UPI = t221.TRAVLR_UPI
 AND t241.TRAVLR_UCI = t221.TRAVLR_UCI
JOIN PQMF.QHBS200_TRAVELLER t200
  ON t221.PNR_REF = t200.PNR_REF
 AND t221.TRAVLR_UCI = t200.TRAVLR_UCI
JOIN PQMF.QHB0260_CM_HISTORY_TRAN x
  ON x.TRAVLR_UCI = t241.TRAVLR_UCI
 AND x.FMFL_ID    = t240.FMFL_ID
 AND x.FL_VERSION_NO = t240.FL_VERSION_NO
JOIN PQMF.QHB0261_CM_HISTORY t261
  ON t261.HIST_TRANS_ID = x.HIST_TRANS_ID
 AND t261.TRANS_SEQ_NO  = x.TRANS_SEQ_NO
 AND t261.FMFL_ID       = x.FMFL_ID
 AND t261.FL_VERSION_NO = x.FL_VERSION_NO
 AND t261.TRAVLR_UCI    = x.TRAVLR_UCI
WHERE
    t261.HIST_IMAGE_TYPE_CODE = 'NEW'
AND t261.HIST_KEYWRD_CODE = 'TGNO'
AND x.SOURCE_APPL_REF = 'CPR'
)
SELECT
    base.*,
    COALESCE(
      (t263.AIRPORT_CODE || ' ' || t263.TERMINAL_CODE || ' ' || t263.LOCATION_CATG_CODE || ' ' || t263.AIRPORT_OR_CITY_IND || ' ' || t263.WORKSTATION_LOCATION_INDEX),
      (t313.AIRPORT_CODE || ' ' || t313.TERMINAL_CODE || ' ' || t313.LOCATION_CATG_CODE || ' ' || t313.AIRPORT_OR_CITY_IND || ' ' || t313.WORKSTATION_LOCATION_INDEX),
      ''
    ) AS WORKSTATION_ID
FROM base
LEFT JOIN PQMF.QHB0263_CHECKIN_LOCATION t263
  ON base.HIST_TRANS_ID = t263.HIST_TRANS_ID
 AND base.TRANS_SEQ_NO  = t263.TRANS_SEQ_NO
 AND base.DEPUPOR       = t263.AIRPORT_CODE
LEFT JOIN PQMF.QHB0313_BAG_CHECKIN_LOCATION t313
  ON base.HIST_TRANS_ID = t313.HIST_TRANS_ID
 AND base.TRANS_SEQ_NO  = t313.TRANS_SEQ_NO
 AND base.DEPUPOR       = t313.AIRPORT_CODE
WHERE
    (base.PNR_REF  = NULLIF(TRIM(?), '') OR NULLIF(TRIM(?), '') IS NULL)
AND (base.PRMEFLTN = NULLIF(TRIM(?), '') OR NULLIF(TRIM(?), '') IS NULL)
AND (base.DEPUPOR  = NULLIF(TRIM(?), '') OR NULLIF(TRIM(?), '') IS NULL)
AND (base.LOCLDEPD >= ? OR ? IS NULL)
AND (base.LOCLDEPD <= ? OR ? IS NULL)
ORDER BY BAG_TAG_UTC_TIMESTAMP DESC;