SELECT DISTINCT
    qcht.OFFICE_ID,
    qcht.USER_SONIC_ID,
    (qbcl.AIRPORT_OR_CITY_IND||'/'||qbcl.AIRPORT_CODE||'/'||qbcl.LOCATION_CATG_CODE||'/'||qbcl.WORKSTATION_LOCATION_INDEX) AS CHECKIN_DETAILS,
    qb.TRAVLR_UCI,
    qb.BAG_UBI_ID,
    qb.TRAVLR_FIRST_NAME,
    qb.TRAVLR_LAST_NAME,
    TRIM(qb.BAG_TAG_CARRIER_NUMBER) || '-' || TRIM(qb.BAG_TAG_AAIRALPC) || '-' || TRIM(qb.BAG_TAG_NUMBER) AS BAG_DETAILS,
    qb.Q_BAG_TAG_ID,
    qb.BAG_DEST_PORT_CODE,
    qcht.ACTIVITY_TSMP
FROM PQMF.QHB0260_CM_HISTORY_TRAN qcht
JOIN PQMF.QHB0313_BAG_CHECKIN_LOCATION qbcl
  ON qcht.HIST_TRANS_ID = qbcl.HIST_TRANS_ID
 AND qcht.FMFL_ID      = qbcl.FMFL_ID
JOIN PQMF.QHBS304_BAG qb
  ON qcht.BAG_UBI_ID  = qb.BAG_UBI_ID
 AND qcht.TRAVLR_UCI  = qb.TRAVLR_UCI
WHERE
    qb.BAG_UBI_ID = NULLIF(TRIM(?), '')
AND (qb.TRAVLR_UCI = NULLIF(TRIM(?), '') OR NULLIF(TRIM(?), '') IS NULL)
ORDER BY qcht.ACTIVITY_TSMP DESC;