SELECT DISTINCT
    qt.PNR_REF, qt.TRAVLR_UCI, qt.TRAVLR_FIRST_NAME, qt.TRAVLR_LAST_NAME,
    qbgitn.AAIRALPC, qbgitn.PRMEFLTN, qbgitn.LOCLDEPD, qbgitn.DEPUPOR, qbgitn.ARVLPOR,
    qb.BAG_UBI_ID AS BAG_SYSTEM_ID,
    RIGHT('0000' || TRIM(qb.BAG_TAG_CARRIER_NUMBER), 4) || '-' || TRIM(qb.BAG_TAG_NUMBER) AS TAG_NUMBER,
    qb.BAG_DEST_PORT_CODE AS BAG_DEST,
    qb.BAG_WGT AS WEIGHT_KG
FROM PQMF.QHBS300_BAG_GROUP qbg
JOIN PQMF.QHB0303_BAG_GROUP_MEMBER qbgm ON qbg.BAG_GROUP_BR_ID = qbgm.BAG_GROUP_BR_ID
JOIN PQMF.QHB0302_BAG_GROUP_ITIN qbgitn ON qbgm.BAG_GROUP_BR_ID = qbgitn.BAG_GROUP_BR_ID
JOIN PQMF.QHBS304_BAG qb ON qbgm.BAG_UBI_ID = qb.BAG_UBI_ID
JOIN PQMF.QHBS200_TRAVELLER qt ON qbg.TRAVLR_UCI = qt.TRAVLR_UCI
WHERE
    (qt.TRAVLR_LAST_NAME  = NULLIF(TRIM(?), '') OR NULLIF(TRIM(?), '') IS NULL)
AND (qt.TRAVLR_FIRST_NAME = NULLIF(TRIM(?), '') OR NULLIF(TRIM(?), '') IS NULL)
AND (qbgitn.AAIRALPC      = NULLIF(TRIM(?), '') OR NULLIF(TRIM(?), '') IS NULL)
AND (qbgitn.PRMEFLTN      = NULLIF(TRIM(?), '') OR NULLIF(TRIM(?), '') IS NULL)
AND (qbgitn.DEPUPOR       = NULLIF(TRIM(?), '') OR NULLIF(TRIM(?), '') IS NULL)
AND (qbgitn.ARVLPOR       = NULLIF(TRIM(?), '') OR NULLIF(TRIM(?), '') IS NULL)
AND (qbgitn.LOCLDEPD >= ? OR ? IS NULL)
AND (qbgitn.LOCLDEPD <= ? OR ? IS NULL)
ORDER BY LOCLDEPD DESC;