SELECT DISTINCT
    t200.PNR_REF,
    t200.TRAVLR_UCI,
    t200.TRAVLR_FIRST_NAME,
    t200.TRAVLR_LAST_NAME,
    t240.AAIRALPC,
    t240.PRMEFLTN,
    t240.LOCLDEPD,
    t240.DEPUPOR,
    t240.ARVLPOR,
    x.ACTIVITY_TSMP,
    x.USER_SONIC_ID,
    x.OFFICE_ID,
    t261.HIST_KEYWRD_CODE,
    t261.HIST_TEXT,
    t261.HIST_IMAGE_TYPE_CODE,
    t261.HIST_TRANS_ID,
    t261.TRANS_SEQ_NO
FROM PQMF.QHB0240_FLIGHT_LEG_DEPART t240
JOIN PQMF.QHB0241_TRAVLR_FLIGHT_LEG t241
  ON t240.FMFL_ID = t241.FMFL_ID
 AND t240.FL_VERSION_NO = t241.FL_VERSION_NO
JOIN PQMF.QHB0221_FLIGHT_ITINERARY t221
  ON t241.TRAVLR_UPI = t221.TRAVLR_UPI
 AND t241.TRAVLR_UCI = t221.TRAVLR_UCI
JOIN PQMF.QHBS200_TRAVELLER t200
  ON t221.PNR_REF = t200.PNR_REF
 AND t221.TRAVLR_UCI = t200.TRAVLR_UCI
JOIN PQMF.QHB0260_CM_HISTORY_TRAN x
  ON x.TRAVLR_UCI = t241.TRAVLR_UCI
 AND x.FMFL_ID = t240.FMFL_ID
 AND x.FL_VERSION_NO = t240.FL_VERSION_NO
JOIN PQMF.QHB0261_CM_HISTORY t261
  ON t261.HIST_TRANS_ID = x.HIST_TRANS_ID
 AND t261.TRANS_SEQ_NO  = x.TRANS_SEQ_NO
 AND t261.FMFL_ID       = x.FMFL_ID
 AND t261.FL_VERSION_NO = x.FL_VERSION_NO
 AND t261.TRAVLR_UCI    = x.TRAVLR_UCI
WHERE
    t261.HIST_IMAGE_TYPE_CODE = 'NEW'
    -- reduce noise: exclude regulatory/document style keys
AND t261.HIST_KEYWRD_CODE NOT IN ('RDDS','RDSN','RDCI','RDCA')
AND t261.HIST_KEYWRD_CODE NOT LIKE 'RD%'
AND (t200.PNR_REF  = NULLIF(TRIM(?), '') OR NULLIF(TRIM(?), '') IS NULL)
AND (t240.PRMEFLTN = NULLIF(TRIM(?), '') OR NULLIF(TRIM(?), '') IS NULL)
AND (t240.DEPUPOR  = NULLIF(TRIM(?), '') OR NULLIF(TRIM(?), '') IS NULL)
AND (t240.ARVLPOR  = NULLIF(TRIM(?), '') OR NULLIF(TRIM(?), '') IS NULL)
AND (t240.LOCLDEPD >= ? OR ? IS NULL)
AND (t240.LOCLDEPD <= ? OR ? IS NULL)
AND (t261.HIST_KEYWRD_CODE = NULLIF(TRIM(?), '') OR NULLIF(TRIM(?), '') IS NULL)
ORDER BY x.ACTIVITY_TSMP DESC;