SELECT DISTINCT
    qt.PNR_REF,
    qt.TRAVLR_UCI,
    qt.TRAVLR_FIRST_NAME,
    qt.TRAVLR_LAST_NAME,
    qbgitn.AAIRALPC,
    qbgitn.PRMEFLTN,
    qbgitn.LOCLDEPD,
    qbgitn.DEPUPOR,
    qbgitn.ARVLPOR,
    xb.XSBG_CALC_XCI_ID,
    xb.EXCESS_AMT_WGT,
    xb.EXCESS_AMT_PCS,
    xb.EXCESS_AMT_CURR_CDE,
    xb.EXCESS_AMT_AMT
FROM PQMF.QHBS300_BAG_GROUP qbg
JOIN PQMF.QHB0303_BAG_GROUP_MEMBER qbgm ON qbg.BAG_GROUP_BR_ID = qbgm.BAG_GROUP_BR_ID
JOIN PQMF.QHB0302_BAG_GROUP_ITIN qbgitn ON qbgm.BAG_GROUP_BR_ID = qbgitn.BAG_GROUP_BR_ID
JOIN PQMF.QHBS200_TRAVELLER qt ON qbg.TRAVLR_UCI = qt.TRAVLR_UCI
JOIN PQMF.QHB0311_BAG_XBAG_ITEM xb ON xb.TRAVLR_UCI = qt.TRAVLR_UCI
WHERE qt.PNR_REF = NULLIF(TRIM(?), '')
ORDER BY LOCLDEPD DESC;