SELECT TOP 2000
    eb.*
FROM PQMF.QHB0312_EXCESS_BAG_NEW eb
WHERE
    (eb.TRAVLR_UCI = NULLIF(TRIM(?), '') OR NULLIF(TRIM(?), '') IS NULL)
AND (eb.LOCLDEPD >= ? OR ? IS NULL)
AND (eb.LOCLDEPD <= ? OR ? IS NULL)
ORDER BY eb.LOCLDEPD DESC;