SELECT
    TBL.FLT,
    TBL.DEP_DATE,
    COUNT(DISTINCT TBL.PAX_ID) AS TOTAL_BKD_PAX,
    SUM(CASE WHEN TBL.ORGL_CABC = 'P' THEN 1 ELSE 0 END) AS BKD_P,
    SUM(CASE WHEN TBL.ORGL_CABC = 'J' THEN 1 ELSE 0 END) AS BKD_J,
    SUM(CASE WHEN TBL.ORGL_CABC = 'W' THEN 1 ELSE 0 END) AS BKD_W,
    SUM(CASE WHEN TBL.ORGL_CABC = 'Y' THEN 1 ELSE 0 END) AS BKD_Y,
    SUM(CASE WHEN TBL.TVLD_STAT_CODE = 'T' THEN 1 ELSE 0 END) AS TOTAL_TVLD_PAX,
    SUM(CASE WHEN TBL.TVLD_STAT_CODE = 'T' AND TBL.ORGL_CABC = 'P' THEN 1 ELSE 0 END) AS TVLD_P,
    SUM(CASE WHEN TBL.TVLD_STAT_CODE = 'T' AND TBL.ORGL_CABC = 'J' THEN 1 ELSE 0 END) AS TVLD_J,
    SUM(CASE WHEN TBL.TVLD_STAT_CODE = 'T' AND TBL.ORGL_CABC = 'W' THEN 1 ELSE 0 END) AS TVLD_W,
    SUM(CASE WHEN TBL.TVLD_STAT_CODE = 'T' AND TBL.ORGL_CABC = 'Y' THEN 1 ELSE 0 END) AS TVLD_Y
FROM (
    SELECT DISTINCT
        qtps.TVLD_STAT_CODE,
        TRIM(qdas.OPRG_CARR_ALPHA_CODE)||' '||TRIM(qdas.OPRG_FLT_NO) AS FLT,
        qtps.ORGL_CABC,
        TRIM(qtp.TP_ID)||'-'||TRIM(qtp.BKG_ID)||'-'||TRIM(qtps.TP_PAX_ID)||'-'||TRIM(qtps.TP_PAX_SEG_ID) AS PAX_ID,
        qdas.depu_locl_date AS DEP_DATE,
        qdas.DEPU_AIPC,
        qdas.ARVL_AIPC,
        qdas.OPRG_CARR_ALPHA_CODE,
        qdas.OPRG_FLT_NO
    FROM PQMF.QMU0101_BKG_REF qbr
    JOIN PQMF.QMUS110_TP_PAX qtp
      ON qbr.TP_ID = qtp.TP_ID AND qbr.BKG_ID = qtp.BKG_ID
     AND qtp.CAN_TXN_ID = 0 AND qbr.CAN_TXN_ID = 0
    JOIN PQMF.QMU0122_TP_PAX_SEG qtps
      ON qtp.TP_ID = qtps.TP_ID AND qtp.BKG_ID = qtps.BKG_ID AND qtp.TP_PAX_ID = qtps.TP_PAX_ID
     AND qtps.CAN_TXN_ID = 0
    JOIN PQMF.QMU0121_TP_AIR_SEG qtas
      ON qtas.TP_ID = qtps.TP_ID AND qtas.BKG_ID = qtps.BKG_ID AND qtas.TP_AIR_SEG_ID = qtps.TP_AIR_SEG_ID
     AND qtas.CAN_TXN_ID = 0
    JOIN PQMF.QMU0120_DATED_AIR_SEG qdas
      ON qtas.DATED_AIR_SEG_ID = qdas.DATED_AIR_SEG_ID
    WHERE
        qdas.OPRG_CARR_ALPHA_CODE = NULLIF(TRIM(?), '')
    AND (qdas.OPRG_FLT_NO = NULLIF(TRIM(?), '') OR NULLIF(TRIM(?), '') IS NULL)
    AND (qdas.DEPU_AIPC = NULLIF(TRIM(?), '') OR NULLIF(TRIM(?), '') IS NULL)
    AND (qdas.ARVL_AIPC = NULLIF(TRIM(?), '') OR NULLIF(TRIM(?), '') IS NULL)
    AND (qdas.depu_locl_date >= ? OR ? IS NULL)
    AND (qdas.depu_locl_date <= ? OR ? IS NULL)
) AS TBL
GROUP BY 1,2
ORDER BY 2,1;
``