WITH RAW_TABLE AS (
    SELECT
        qbr.BKG_REF_NO,
        qdas.OPRG_CARR_ALPHA_CODE,
        qtp.TRAVLR_UCI,
        CASE WHEN qdas.OPRG_FLT_NO <> '' THEN 1 ELSE 0 END AS FLIGHT_COUNT,
        qdas.OPRG_FLT_NO,
        qdas.DEPU_AIPC,
        qdas.ARVL_AIPC,
        (T01D.CTRYCOD||T01A.CTRYCOD) AS FLT_TYPE,
        CASE WHEN (T01D.CTRYCOD||T01A.CTRYCOD) = 'AUAU' THEN 0 ELSE 1 END AS IS_INT_FLIGHT,
        qdas.depu_locl_date AS DEP_DATE
    FROM PQMF.QMU0101_BKG_REF qbr
    JOIN PQMF.QMUS110_TP_PAX qtp
      ON qbr.TP_ID = qtp.TP_ID AND qbr.BKG_ID = qtp.BKG_ID
     AND qtp.CAN_TXN_ID = 0 AND qbr.CAN_TXN_ID = 0
    JOIN PQMF.QMU0122_TP_PAX_SEG qtps
      ON qtp.TP_ID = qtps.TP_ID AND qtp.BKG_ID = qtps.BKG_ID AND qtp.TP_PAX_ID = qtps.TP_PAX_ID
     AND qtps.CAN_TXN_ID = 0
    JOIN PQMF.QMU0121_TP_AIR_SEG qtas
      ON qtas.TP_ID = qtps.TP_ID AND qtas.BKG_ID = qtps.BKG_ID AND qtas.TP_AIR_SEG_ID = qtps.TP_AIR_SEG_ID
     AND qtas.CAN_TXN_ID = 0
    JOIN PQMF.QMU0120_DATED_AIR_SEG qdas
      ON qtas.DATED_AIR_SEG_ID = qdas.DATED_AIR_SEG_ID
    LEFT JOIN PQMF.QLO0001_AIRPORT T01D ON T01D.AIRPCOD = qdas.DEPU_AIPC
    LEFT JOIN PQMF.QLO0001_AIRPORT T01A ON T01A.AIRPCOD = qdas.ARVL_AIPC
    WHERE
        (qbr.BKG_REF_NO = NULLIF(TRIM(?), '') OR NULLIF(TRIM(?), '') IS NULL)
    AND (qtp.TRAVLR_UCI = NULLIF(TRIM(?), '') OR NULLIF(TRIM(?), '') IS NULL)
    AND (qdas.depu_locl_date >= ? OR ? IS NULL)
    AND (qdas.depu_locl_date <= ? OR ? IS NULL)
),
AGG AS (
    SELECT
        BKG_REF_NO AS PNR,
        TRAVLR_UCI,
        SUM(FLIGHT_COUNT) AS SEGMENTS_BY_PNR,
        MIN(DEP_DATE) AS DEP_DATE,
        SUM(IS_INT_FLIGHT) AS INT_SEG_COUNT
    FROM RAW_TABLE
    GROUP BY 1,2
)
SELECT
    PNR,
    TRAVLR_UCI,
    CAST(SEGMENTS_BY_PNR AS INTEGER) AS SEGMENTS_BY_PNR,
    DEP_DATE,
    CASE WHEN INT_SEG_COUNT = 0 THEN 'DOM' ELSE 'INTL' END AS IS_INTL
FROM AGG
ORDER BY DEP_DATE DESC, PNR, TRAVLR_UCI;